[
  "Bonus Audio::Domain Blip::__NI_SMPL_ADD__",
  "Bonus Audio::Fast PWM::(2016614 203125)",
  "Bonus Audio::Filter Vox::(2016614 21229)",
  "Bonus Audio::FilterBell::Processed Samples",
  "Bonus Audio::Gracie::(2016725 144330)",
  "Bonus Audio::MET::__NI_SMPL_ADD__",
  "Bonus Audio::NO RES SAW::Examples",
  "Bonus Audio::NO RES SAW::Processed Samples",
  "Bonus Audio::OX::(2016726 151719)",
  "Bonus Audio::Pals::(2016616 221031)",
  "Bonus Audio::SampleChord::Processed Samples",
  "Bonus Audio::SimpleSeq::Simple Seq 125",
  "Bonus Audio::sys101 STO Detuned Squares::(20161026 03731)",
  "Bonus Audio::sys101 STO FM::(20161025 201132)",
  "Bonus Audio::sys101 STO Two note thing::(20161026 2451)",
  "Bonus Audio::Wet Triangle::Processed Samples",
  "Misc::2FINGERS::(201279 18448)",
  "Misc::ADDVERB::(201279 17429)",
  "Misc::all blip::all blip",
  "Misc::Another Time::(201631 92224)",
  "Misc::BEDNOTCH::(201279 162618)",
  "Misc::Big Stack::(2012619 221412)",
  "Misc::Bison::(2012621 161950)",
  "Misc::Bug Lad::(2012621 193922)",
  "Misc::Chill Em::__NI_SMPL_ADD__",
  "Misc::Classy Pluck::__NI_SMPL_ADD__",
  "Misc::Confused Waves::__NI_SMPL_ADD__",
  "Misc::Death Perc::__NI_SMPL_ADD__",
  "Misc::Detune Mod::Detune Mod",
  "Misc::Easier Said::__NI_SMPL_ADD__",
  "Misc::Electric Seas::__NI_SMPL_ADD__",
  "Misc::FM Drama::(2012621 2068)",
  "Misc::FM Snare::__NI_SMPL_ADD__",
  "Misc::FM Thickness::(2016227 15155)",
  "Misc::Fm Zap Kick::__NI_SMPL_ADD__",
  "Misc::FM1::(2016331 42827)",
  "Misc::FM12::(2016331 51222)",
  "Misc::FM1filt::(2016331 45027)",
  "Misc::Goose Fat::__NI_SMPL_ADD__",
  "Misc::Gravy Dinner::__NI_SMPL_ADD__",
  "Misc::gud bell::__NI_SMPL_ADD__",
  "Misc::Hat 2::__NI_SMPL_ADD__",
  "Misc::hat 3::__NI_SMPL_ADD__",
  "Misc::Heavy Hearts::__NI_SMPL_ADD__",
  "Misc::Im the only 1 u need::__NI_SMPL_ADD__",
  "Misc::Jab at me::__NI_SMPL_ADD__",
  "Misc::Losen::(2016314 231137)",
  "Misc::low kick::__NI_SMPL_ADD__",
  "Misc::Lowering Standards::(201631 5942)",
  "Misc::Manly Bass::(201631 5228)",
  "Misc::ManyMultiBlip::__NI_SMPL_ADD__",
  "Misc::MELOWMOD::(201279 182145)",
  "Misc::MPesque::(2012621 144834)",
  "Misc::Noisy Triangle LP 3 4p::Noisy Triangle LP 3 4p",
  "Misc::Noize Baz::__NI_SMPL_ADD__",
  "Misc::non::(201633 75014)",
  "Misc::pad source::Pad source",
  "Misc::PHASEDPAD::(201279 171756)",
  "Misc::Pulse Demon::__NI_SMPL_ADD__",
  "Misc::pw 0-64::(2016331 3040)",
  "Misc::PW Filter::(2016331 34425)",
  "Misc::PW Mod::(2016331 4629)",
  "Misc::quick filter sweep::Quick Filter Sweep",
  "Misc::Short Kick::__NI_SMPL_ADD__",
  "Misc::short nki::Audio",
  "Misc::Short Stack::__NI_SMPL_ADD__",
  "Misc::Short Waves::BPPULSE Samples",
  "Misc::Short Waves::BPPULSE-SHORT",
  "Misc::Short Waves::Disturber",
  "Misc::Short Waves::Electric Samples",
  "Misc::Short Waves::Feed Samples",
  "Misc::Short Waves::Feedy",
  "Misc::Short Waves::Heaving Samples",
  "Misc::Short Waves::Heavy Hearts",
  "Misc::Short Waves::non",
  "Misc::Short Waves::nzb",
  "Misc::Short Waves::Phase Lead",
  "Misc::Short Waves::Phase Samples",
  "Misc::Short Waves::PULSEBP4P Samples",
  "Misc::Short Waves::PULSEBP4P-SHORT",
  "Misc::Short Waves::SAW HILO-SHORT",
  "Misc::Short Waves::SAW LP-4P HI-RES-SHORT",
  "Misc::Short Waves::SAW-3PHASELOW-SHORT",
  "Misc::Short Waves::SAW-BP-4P-SHORT",
  "Misc::Short Waves::SAW-HILOWRES-SHORT",
  "Misc::Short Waves::SAW-HP-1P -SHORT",
  "Misc::Short Waves::SAW-LP-1P",
  "Misc::Short Waves::SAW-LP-1P HI-RES",
  "Misc::Short Waves::SAW-LP-1P MID-RES",
  "Misc::Short Waves::SAW-LP-2P",
  "Misc::Short Waves::SAW-LP-2P HI-RES",
  "Misc::Short Waves::SAW-LP-2P MID-RES",
  "Misc::Short Waves::SAW-LP-3P",
  "Misc::Short Waves::SAW-LP-3P HI-RES",
  "Misc::Short Waves::SAW-LP-3P MID-RES",
  "Misc::Short Waves::SAW-LP-4P",
  "Misc::Short Waves::SAW-LP-4P HI-RES",
  "Misc::Short Waves::SAW-LP-4P MID-RES",
  "Misc::Short Waves::SAW-PHS-LOW-SHORT",
  "Misc::Short Waves::SAW1PHIRES Samples",
  "Misc::Short Waves::SAW1PMIDRES Samples",
  "Misc::Short Waves::SAW2PHIRES Samples",
  "Misc::Short Waves::SAW2PMIDRES Samples",
  "Misc::Short Waves::SAW3PHASE1LP Samples",
  "Misc::Short Waves::SAW4PBP-SHORT",
  "Misc::Short Waves::SAWHILOW Samples",
  "Misc::Short Waves::SAWLP1P  Samples",
  "Misc::Short Waves::SAWLP2P Samples",
  "Misc::Short Waves::SAWLP4P Samples",
  "Misc::Short Waves::SAWPHASE-SHORT",
  "Misc::Short Waves::SAWX2-3HI1LO-SHORT",
  "Misc::Short Waves::SAWx2-LP-1P HI-RES",
  "Misc::Short Waves::SAWX2-LP-2P MID-RES",
  "Misc::Short Waves::SAWX2-LP-3P MID-RES",
  "Misc::Short Waves::Some More Samples",
  "Misc::Short Waves::Some Samples",
  "Misc::Short Waves::SQR-BP-4P-SHORT",
  "Misc::Short Waves::SQR-HILOWI-RES-SHORT",
  "Misc::Short Waves::SQR-HP-1P-SHORT",
  "Misc::Short Waves::SQR-HP-3P -SHORT",
  "Misc::Short Waves::SQR-HP-3P-SHORT",
  "Misc::Short Waves::SQR-LP-1P",
  "Misc::Short Waves::SQR-LP-1P 2-SHORT",
  "Misc::Short Waves::SQR-LP-1P HI-RES",
  "Misc::Short Waves::SQR-LP-1P MID-RES",
  "Misc::Short Waves::SQR-LP-2P",
  "Misc::Short Waves::SQR-LP-2P HI-RES",
  "Misc::Short Waves::SQR-LP-2P MID-RES",
  "Misc::Short Waves::SQR-LP-3P",
  "Misc::Short Waves::SQR-LP-3P HI-RES",
  "Misc::Short Waves::SQR-LP-3P MID-RES",
  "Misc::Short Waves::SQR-LP-4P",
  "Misc::Short Waves::SQR-LP-4P HI-RES",
  "Misc::Short Waves::SQR-LP-4P HI-RES-SHORT",
  "Misc::Short Waves::SQR-NOTCHLOW-SHORT",
  "Misc::Short Waves::SQR-NTCH-LOW-SHORT",
  "Misc::Short Waves::SQR-PHASE-SHORT",
  "Misc::Short Waves::SQR3HI1LO-SHORT",
  "Misc::Short Waves::SQRX2-LP-4P MID-RES",
  "Misc::Short Waves::TRI-BP-3P-SHORT",
  "Misc::Short Waves::TRI-HILOWW-SHORT",
  "Misc::Short Waves::TRI-LP-1P",
  "Misc::Short Waves::TRI-LP-4P HI-RES",
  "Misc::Short Waves::TRI-LP-4P HI-RES-SHORT",
  "Misc::Short Waves::TRINOTCH-SHORT",
  "Misc::Sine::Sine",
  "Misc::Sine 2 FM::Sine 2 FM",
  "Misc::Sine Piano::(201631 9754)",
  "Misc::Spring::(2012621 154828)",
  "Misc::Sweeped Sync::Sweeped Sync",
  "Misc::Sweeping Mild FM::Sweeping Mild FM",
  "Misc::Swirl N Wirl::Swirl N Wirl",
  "Misc::Tap Tap::Tap Tap",
  "Misc::Telapia::(2016229 203658)",
  "Misc::The Bumps::(2016229 181633)",
  "Misc::Thick Shiner::__NI_SMPL_ADD__",
  "Misc::Thick Snappy::(201631 44227)",
  "Misc::Thin Shiner::__NI_SMPL_ADD__",
  "Misc::touch lfo::touch lfo",
  "Misc::Tracker::__NI_SMPL_ADD__",
  "Misc::Tube String::__NI_SMPL_ADD__",
  "Misc::Vel 2 Osc 2::Vel 2 Osc 2",
  "Misc::Vel to LFO::Vel to LFO",
  "Misc::Vel to Osc::Vel to Osc",
  "Misc::Vox Bass FX::(201631 6436)",
  "Misc::Vox FX::__NI_SMPL_ADD__",
  "Misc::Vox Lead::(201631 54834)",
  "Misc::Warm Thickly::(2016328 101540)",
  "Misc::Water FM::(201631 0357)",
  "Misc::Weirdo Pluck::__NI_SMPL_ADD__",
  "Misc::xp-atl-filter2vel::__NI_SMPL_ADD__",
  "Misc::ZX::(201279 163740)"
]